### ISSUE TITLE
Re-Do the HUD

### ISSUE THREAD

**Issue by doctorluk** [doctorluk/Reign-of-the-Undead-Revolution-Scripts#10]
Overhaul the in game HUD for all players, especially change the weapon ammo display to enable individual low-ammo display as we plan to have all guns have 1000 ammo max.

Maybe use assets from RoZO?

**Comment by DuncanCasteleyn** [comment]
Why no just use a the ammo counters from Promod?

**Comment by doctorluk** [comment]
We aim to have the hosts configure the order of weapons. For this we have to set each weapon's max. ammo to 1000 in their weapon files and set their actual maximum value via script. Due to this we also have to make our own "low-ammo" warning by setting a cvar when the current ammo is below 30% of the actual script-fed ammo.
