### ISSUE TITLE
Scripts Bug icons and buttons 

### ISSUE THREAD

**Issue by aramo44** [doctorluk/Reign-of-the-Undead-Revolution-Scripts#5]
hello mate i found some bugs in rotus script 
1- the icons of medic on screen is radar not medic icon and medkit placed is c4 icon 
2-the ammo box icon on screen is airstrike icon and ammobox placed is c4 icon .
i checked setting in script both is fine but idont know where is the problem 
3-if you bought turrets (both kinds) ,, when we put the turrets if we change turrets location second time the Pressed button F will bugged and we cannot buy anything ammo,cures,,c4,.....  or upgrade weapons .

idont know exactly where to change number of times that we can change turret location by default its 1 attempt and after that F buuton bugged and no more works .
thnks .

**Comment by doctorluk** [comment]
Turrets should be replaceable an infinite amount of times (until they run out of juice ofc).

The other bugs are most likely caused by our weapons system getting an overhaul, which is not complete, yet.

Thanks for the report!
