### ISSUE TITLE
Make weapon stats scale via script

### ISSUE THREAD

**Issue by doctorluk** [doctorluk/Reign-of-the-Undead-Revolution-Scripts#8]
Make all weapons upgrade their max ammo, max/min damage, damage distance falloff depending on their upgrade state independent from their weapon file setting, enabling everyone to change the order of weapons without having to hassle with the weapon files.

**Comment by 3aGl3** [comment]
Resolved with 1647f598fcc4640a92b5a3c0ee59ac9beb32267e
